### PR TITLE
Add Ukrainian localization

### PR DESCRIPTION
**Pull request by andmizyk**
# Description 

Remind me if i forgot something

# Copyright assignment 

Pull request authors must assign the copyright of their contributions to the author of Orgro, [@amake](https://github.com/amake) ([find out why](https://github.com/amake/orgro/blob/master/.github/contributing.md#do-you-want-to-contribute-a-feature-or-bug-fix)).

- [x] I hereby assign the copyright for the contributions herein to @amake. I understand that I will no longer retain any rights relating to the contributions except those provided by the GPL-3.0 license.

### CODE REVIEW

**Comment by amake** [comment]
Thanks very much! I think you've got everything, but I will double-check.

This is the first non-trivial contribution to Orgro, so I apologize for not being ready with this but: In order for Orgro to continue to be distributable on the Apple App Store, I need all contributors to assign the copyright for their contributions to me. Please see [here](https://github.com/amake/orgro/blob/39b84322845da28e0a634ede0336df047fe292c3/.github/contributing.md#do-you-want-to-contribute-a-feature-or-bug-fix) for details.

I have edited your comment above to apply the new PR template I just pushed. If you agree to assign copyright, please check the checkbox. If you prefer not to assign copyright, then that's OK too; you can just close the PR in that case.

**Comment by andmizyk** [comment]
Yes, sure.
Thank you for the nice app.

**Comment by amake** [comment]
I've put up a beta release with your localization. If you can, please check that everything appears correctly:

- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)
- [iOS](https://testflight.apple.com/join/8YTxcuZC) (will be ready soon; the version will be 1.23.0)

**Comment by andmizyk** [comment]
I can’t install, because I use the f-droid. But I think everything should be good. I hope this version will appear on f-droid?

**Comment by amake** [comment]
Ah, sure, sorry. I usually publish to F-Droid last because there's no way to do a pre-release.

I've now pushed the source for 1.23.0, so you can run it locally if you know how (`flutter run` from the root of the repository).

**Comment by amake** [comment]
Great! I've posted a [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10193) to get 1.23.0 into F-Droid, so it should show up for you in a few days.

**Comment by amake** [comment]
This is now live on all platforms.

**Pull request closed without merging**
